### ISSUE TITLE
Notebook outline suggestions

### ISSUE THREAD

**Issue by charlesbluca** [andersy005/intake-pangeo-catalog-EarthCube-2020#1]
Opening this up for general discussion on the outline of the notebook - based on the abstract and suggestions from @andersy005:

- Introduction of situation (maybe displaying an example of huge climate data?)
- Demonstration of intake/intake-esm
    - Accessing example local/remote catalogs
    - Exploring metadata, loading datasets into containers
- Showcase Pangeo catalog
    - Access ESM collections in Pangeo catalog
    - Browse online catalog (embed video?)

Anything else we could add?

**Comment by andersy005** [comment]
Thank you for putting this together, @charlesbluca! 

> Introduction of situation (maybe displaying an example of huge climate data?)

I was thinking that we could use the CMIP6 archive copies in both GCP and on NCAR's filesystem in order to demonstrate the value of data catalogues when it comes to workflow reproducibility in an HPC/Cloud environment.

**Comment by andersy005** [comment]
@charlesbluca, when you get a chance, can you take a look at the [example notebook](https://github.com/andersy005/intake-pangeo-catalog-EarthCube-2020/blob/master/example.ipynb)? It is not done yet though :) Feel free to modify  it as you see fit.

**Comment by charlesbluca** [comment]
Thanks for the work on the example! I will fill it in with some examples of the Pangeo catalog in use.
